### ISSUE TITLE
Segmentation fault when delivering music

### ISSUE THREAD

**Issue by LinusU** [Floby/node-libspotify#41]
``` text
[../deps/mpg123/src/output/coreaudio.c:81] warning: Didn't have any audio data in callback (buffer underflow)

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x0000000000000000
0x000008c4719245b9 in ?? ()
(gdb) bt
#0  0x000008c4719245b9 in ?? ()
#1  0x000008c4719118b7 in ?? ()
#2  0x000000010018a28c in v8::internal::Invoke ()
#3  0x0000000100146364 in v8::Function::Call ()
#4  0x00000001021055b4 in read_delivered_music (handle=<value temporarily unavailable, due to optimizations>, status=<value temporarily unavailable, due to optimizations>) at ../src/player.cc:132
#5  0x000000010012f60c in uv__run_timers ()
#6  0x0000000100125f7e in uv_run ()
#7  0x000000010000c6e3 in node::Start ()
#8  0x00000001000039f4 in start ()
(gdb) 
```

**Comment by IainCole** [comment]
Looks like this didn't work :(

**Comment by IainCole** [comment]
This one https://github.com/IainCole/node-libspotify/commit/d9f97f0d58803f8cd203919279f4048568c33118 might work better though

**Comment by timpoultney** [comment]
Did it Iain?

**Comment by IainCole** [comment]
I still get a segfault in my particular app but I don't get this error any more and it's much more stable, so I think it worked for fixing this issue. I haven't been able to get to the root cause of my other issue though so there might still be something wrong.
